# These are supported funding model platforms

custom: ['https://paypal.me/smirnoveduard', 'https://www.buymeacoffee.com/smied', 'https://www.bountysource.com/teams/smied']
patreon: Smied
ko_fi: smied
open_collective: smied
github: Smi-ed
